name: Build app and update Docker image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set variables
        id: vars
        run: |
          echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
          echo "docker_image=ghcr.io/netwerk-digitaal-erfgoed/omeka-s-faq" >> $GITHUB_OUTPUT
          echo "deployment=statefulset/omeka-s-faq" >> $GITHUB_OUTPUT

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2.5.0

      - name: Log in to Docker registry
        uses: docker/login-action@v2.1.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CONTAINER_REGISTRY_TOKEN }}

      - name: Build and push image to registry
        uses: docker/build-push-action@v4.0.0
        with:
          context: .
          push: true
          tags: |
            ${{ steps.vars.outputs.docker_image }}:${{ steps.vars.outputs.sha_short }}
            ${{ steps.vars.outputs.docker_image }}:latest

      - uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Store DigitalOcean credentials
        run: doctl kubernetes cluster kubeconfig save nde

      - name: Update deployment
        run: |
          kubectl set image ${{ steps.vars.outputs.deployment }} app=${{ steps.vars.outputs.docker_image }}:${{ steps.vars.outputs.sha_short }} --record

      - name: Verify
        run: kubectl rollout status ${{ steps.vars.outputs.deployment }}
